/*
* ==============================================================================
*        %name: exports.inc %
*     %version: 13 %
*         Name: NssVasCRRD.h
*      Part of: NssVAS / NssVASApi
*  Description: VAS Exports for external clients
*
*  Copyright © 2004-2006 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/

#include <platform_paths.hrh>

../nssvasdb/inc/10201afe.spd                                       /epoc32/release/winscw/udeb/z/private/100012a5/policy/10201afe.spd
../nssvasdb/inc/10201afe.spd                                       /epoc32/release/winscw/urel/z/private/100012a5/policy/10201afe.spd
../nssvasdb/inc/10201afe.spd                                       /epoc32/data/z/private/100012a5/policy/10201afe.spd
