/*
* ==============================================================================
*        %name: exports.inc %
*     %version: 15 %
*      Part of: VoiceUIPluginFramework / VCommandManager
*  Description: VCommandManager exports
*
*  Copyright © 2006-2007 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/



//..\inc\voicecommands.xml               \epoc32\data\z\private\102818E7\voicecommands.xml
//..\inc\voicecommands.xml               \epoc32\release\winscw\udeb\z\private\102818E7\voicecommands.xml
//..\inc\voicecommands.xml               \epoc32\release\winscw\urel\z\private\102818E7\voicecommands.xml

../inc/defaultvoicecommands.xml        /epoc32/data/z/private/102818e7/defaultvoicecommands.xml
../inc/defaultvoicecommands.xml        /epoc32/release/winscw/udeb/z/private/102818e7/defaultvoicecommands.xml
../inc/defaultvoicecommands.xml        /epoc32/release/winscw/urel/z/private/102818e7/defaultvoicecommands.xml

../inc/btvoicecommands.xml             /epoc32/data/z/private/102818e7/btvoicecommands.xml
../inc/btvoicecommands.xml             /epoc32/release/winscw/udeb/z/private/102818e7/btvoicecommands.xml
../inc/btvoicecommands.xml             /epoc32/release/winscw/urel/z/private/102818e7/btvoicecommands.xml

../inc/emailvoicecommands.xml          /epoc32/data/z/private/102818e7/emailvoicecommands.xml
../inc/emailvoicecommands.xml          /epoc32/release/winscw/udeb/z/private/102818e7/emailvoicecommands.xml
../inc/emailvoicecommands.xml          /epoc32/release/winscw/urel/z/private/102818e7/emailvoicecommands.xml

../inc/imvoicecommands.xml             /epoc32/data/z/private/102818e7/imvoicecommands.xml
../inc/imvoicecommands.xml             /epoc32/release/winscw/udeb/z/private/102818e7/imvoicecommands.xml
../inc/imvoicecommands.xml             /epoc32/release/winscw/urel/z/private/102818e7/imvoicecommands.xml

../inc/radiovoicecommands.xml          /epoc32/data/z/private/102818e7/radiovoicecommands.xml
../inc/radiovoicecommands.xml          /epoc32/release/winscw/udeb/z/private/102818e7/radiovoicecommands.xml
../inc/radiovoicecommands.xml          /epoc32/release/winscw/urel/z/private/102818e7/radiovoicecommands.xml

../inc/realplayervoicecommands.xml     /epoc32/data/z/private/102818e7/realplayervoicecommands.xml
../inc/realplayervoicecommands.xml     /epoc32/release/winscw/udeb/z/private/102818e7/realplayervoicecommands.xml
../inc/realplayervoicecommands.xml     /epoc32/release/winscw/urel/z/private/102818e7/realplayervoicecommands.xml

../inc/vrvoicecommands.xml             /epoc32/data/z/private/102818e7/vrvoicecommands.xml
../inc/vrvoicecommands.xml             /epoc32/release/winscw/udeb/z/private/102818e7/vrvoicecommands.xml
../inc/vrvoicecommands.xml             /epoc32/release/winscw/urel/z/private/102818e7/vrvoicecommands.xml

../inc/dictvoicecommands.xml           /epoc32/data/z/private/102818e7/dictvoicecommands.xml
../inc/dictvoicecommands.xml           /epoc32/release/winscw/udeb/z/private/102818e7/dictvoicecommands.xml
../inc/dictvoicecommands.xml           /epoc32/release/winscw/urel/z/private/102818e7/dictvoicecommands.xml

../inc/mmspostcardvoicecommands.xml    /epoc32/data/z/private/102818e7/mmspostcardvoicecommands.xml
../inc/mmspostcardvoicecommands.xml    /epoc32/release/winscw/udeb/z/private/102818e7/mmspostcardvoicecommands.xml
../inc/mmspostcardvoicecommands.xml    /epoc32/release/winscw/urel/z/private/102818e7/mmspostcardvoicecommands.xml
