/*
* ==============================================================================
*        %name: exports.inc %
*     %version: be1sido#18.2.20 %
*      Part of: VoiceUI / VoiceUiNameDialer
*  Description: VoiceUiNameDialer exports
*
*  Copyright (C) 2006-2007 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing,  adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
*
* ============================================================================
*/

#include <platform_paths.hrh>

../data/namediallerstarttone.wav  /epoc32/release/wins/urel/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/wins/udeb/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/winscw/urel/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/winscw/udeb/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/thumb/urel/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/thumb/udeb/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/armv5/urel/z/system/sounds/digital/namediallerstarttone.wav
../data/namediallerstarttone.wav  /epoc32/release/armv5/udeb/z/system/sounds/digital/namediallerstarttone.wav

../data/namediallerconfirmtone.wav  /epoc32/release/wins/urel/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/wins/udeb/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/winscw/urel/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/winscw/udeb/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/thumb/urel/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/thumb/udeb/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/armv5/urel/z/system/sounds/digital/namediallerconfirmtone.wav
../data/namediallerconfirmtone.wav  /epoc32/release/armv5/udeb/z/system/sounds/digital/namediallerconfirmtone.wav

../data/btnamediallerstarttone.wav  /epoc32/release/winscw/urel/z/system/sounds/digital/btnamediallerstarttone.wav
../data/btnamediallerstarttone.wav  /epoc32/release/winscw/udeb/z/system/sounds/digital/btnamediallerstarttone.wav
../data/btnamediallerstarttone.wav  /epoc32/release/armv5/urel/z/system/sounds/digital/btnamediallerstarttone.wav
../data/btnamediallerstarttone.wav  /epoc32/release/armv5/udeb/z/system/sounds/digital/btnamediallerstarttone.wav

../loc/vuivoicerecognition.loc      APP_LAYER_LOC_EXPORT_PATH(vuivoicerecognition.loc)


