/*
* ==============================================================================
*        %name: exports.inc %
*     %version: 2 %
*      Part of: srsf
*  Description: voice commands exports
*
*  Copyright © 2006-2007 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/

#include <platform_paths.hrh>
../loc/defaultvoicecommands.loc APP_LAYER_LOC_EXPORT_PATH(defaultvoicecommands.loc)

