/*
* ==============================================================================
*        %name: testmmpfiles.inc %
*     %version: 6 %
*      Part of: SRSF / VCommandHandler
*  Description: List of test mmp files for the VCommandHandler modules.
*               To be included into bld.infs
*
*  Copyright c 2006 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/

..\internal\tsrc\VcsPrimTest\group\VcsPrimTest.mmp
..\internal\tsrc\VcsUnitTest\group\VcsUnitTest.mmp
..\internal\tsrc\VCommandVasTest\group\VCommandVasTest.mmp
..\internal\tsrc\VCommandHandlerTest\group\VCommandHandlerTest.mmp
..\internal\tsrc\TagCommandConverterTest\group\TagCommandConverterTest.mmp
..\internal\tsrc\MultiUseTest\group\MultiUseTest.mmp
..\internal\tsrc\IntPropertyWatcherTest\group\IntPropertyWatcherTest.mmp
..\internal\tsrc\VcsMultiThreadingTest\group\VcsMultiThreadingTest.mmp